import click
from vcffuse import CreateSVGPicture, SnpEffParser, ExonCoords, FusionMaker

# This is the surrogate for main(): everything happens here
@click.command(context_settings=dict(help_option_names=['-h', '--help']))
@click.option('--vcf', '-v', type=str,
              help='VCF file to get SVs generated by Manta and annotated by snpEff',
              required=True)
@click.option('--svg', '-s', type=str,
              help='The output SVG file name',
              required=True)
@click.option('--rest/--no-rest', '-r', type=bool,
              help='Read from ENSEMBL REST or JSON file',
              required=False,
              default=True)
def print_SV(vcf, svg, rest):
    pass

if __name__ == "__main__":
    print_SV()